name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Check for Gemfile changes
        id: gemfile_changes
        run: |
          git fetch origin main
          git diff --name-only FETCH_HEAD HEAD | grep -q '^Gemfile$' && echo "Gemfile changed" || echo "Gemfile not changed"
      - name: Install dependencies if Gemfile changed
        if: steps.gemfile_changes.outputs.result == 'Gemfile changed'
        run: |
          bundle install
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add Gemfile.lock
          git commit -m "Update Gemfile.lock"
          git push origin main
      - name: Build with Jekyll
        run: bundle exec jekyll build
